### ISSUE TITLE
Output timeout with long running helm chart upgrade

### ISSUE THREAD

**Issue by agentreno** [CircleCI-Public/helm-orb#19]
### Orb version

0.2.3

### What happened

The upgrade-helm-chart command timed out because it took longer than 10 minutes without any output. With wait=true, some charts can take a while to become ready.

### Expected behavior

Ideally the [no_output_timeout](https://circleci.com/docs/2.0/configuration-reference/#run) option should be exposed as a parameter, or the existing timeout parameter for helm should also be applied to no_output_timeout internally in the orb.

**Comment by lokst** [comment]
@agentreno Thank you for your report; we'll be looking to fix this.

**Comment by lokst** [comment]
Resolved in version 1.0.0 of the orb.
