### ISSUE TITLE
Install Helm 2 client fails sometimes during the build

### ISSUE THREAD

**Issue by gauravkohli** [CircleCI-Public/helm-orb#20]
### Orb version
0.2.1

### What happened
we have a step in our workflow which install the helm client version v2.15.1 
`      - helm/install-helm-client:
          version: "v2.15.1"
`
But on some of the builds the install of helm client fails with the following error

> 

    #!/bin/bash -eo pipefail
    if which helm > /dev/null; then
      echo "helm is already installed"
      exit 0
    fi
    VERSION="v2.15.1"
    if [ -n "${VERSION}" ]; then
      set -- "$@" --version "${VERSION}"
    fi
    INSTALL_SCRIPT="https://raw.githubusercontent.com/helm/helm/master/scripts/get"
    curl "${INSTALL_SCRIPT}" > get_helm.sh
    chmod 700 get_helm.sh
    ./get_helm.sh "$@"
    helm init --client-only
      % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                    Dload  Upload   Total   Spent    Left  Speed

    100    26  100    26    0     0      2      0  0:00:13  0:00:12  0:00:01     6
    ./get_helm.sh: line 1: 500:: command not found

    Exited with code exit status 127

### Expected behavior

Ideally and in most of the builds helm client is successfully installed on the kubernetes cluster

**Comment by lokst** [comment]
@gauravkohli Thank you for the report! We will look into an alternative way to install the helm client.

**Comment by dsayling** [comment]
@gauravkohli - Can you tell us what environments you are seeing this issue, i.e. a specific VM executor? or a specific docker image? These details can help us reproduce and narrow further.

**Comment by brivu** [comment]
Hey @gauravkohli , 

Helm 2 has been full deprecated as of [November 2020](https://helm.sh/blog/helm-v2-deprecation-timeline/).  The orb already has support for Helm 3. 

I'm going to close this issue for now.  

Best, 
Brian
