### ISSUE TITLE
Specify path to values file when installing a helm chart

### ISSUE THREAD

**Issue by bobbywatson3** [CircleCI-Public/helm-orb#21]
## What would you like to be added

Ability to pass values files to install-helm-chart, similar to how helm install -f works. That allows environment-specific values files like values.production.yaml to be installed using this orb.

## Why is this needed

We're currently able to override specific values using values-to-override, which works if you only want to override just a few values but doesn't scale well if you have separate values files for reach environment.

**Comment by bobbywatson3** [comment]
Related: https://github.com/CircleCI-Public/aws-eks-orb/issues/23

**Comment by brivu** [comment]
Hey @bobbywatson3, 

Thanks for your suggestion.  I've assigned this issue to myself and will be taking a look as soon as I can.  

Best, 
Brian

**Comment by brivu** [comment]
Hey @bobbywatson3, 

Can you provide me an example of what you're looking for?  The command or documentation of what you're looking for would be super helpful here. 

Let me know so I can get this feature added! 

Best, 
Brian

**Comment by bobbywatson3** [comment]
This is no longer an issue as we no longer use circle CI.
