### ISSUE TITLE
When using helm 3 helm-install-chart fails with Error: unknown flag: --name

### ISSUE THREAD

**Issue by onelittleant** [CircleCI-Public/helm-orb#24]
### Orb version
circleci/helm@0.2.3 using helm 3
`- install-helm-client:
          version: v3.0.0`

### What happened
On install-helm-chart when using helm v3+
Error: unknown flag: --name

### Expected behavior
instead of using a --name flag the RELEASE_NAME should be inserted as an argument to helm install before the chart name.  this is a change from helm 2 to helm 3:
helm2:
`Usage:
  helm install [CHART] [flags]`
helm3:
`Usage:
  helm install [NAME] [CHART] [flags]`
and --name is not a flag in helm 3

**Comment by lokst** [comment]
@onelittleant Thanks for the report, I'll look into a fix!

**Comment by lokst** [comment]
Resolved in version 1.0.0 of the orb.
