### ISSUE TITLE
Helm init breaks on helm version < v2.17 due to deprecation of stable chart repo

### ISSUE THREAD

**Issue by schuylerfried** [CircleCI-Public/helm-orb#34]
### Breaks on helm < v2.17 init due to deprecation of stable chart repo

I use this orb specifically for helm-install-client, and as of today, the repo for stable charts, which had been deprecated a while ago is no longer available. See blog post: https://helm.sh/blog/new-location-stable-incubator-charts/.

If you try and call `helm init --client-only` after installing helm <v2.17, it tries to add the old stable repo location, and you get a 403 code. The solution is to run `helm init --client-only --stable-repo-url https://charts.helm.sh/stable`

**Comment by dsayling** [comment]
#35 should fix this in orb version `1.2.0`. The new version also includes the ability to specify a different helm repo beyond the default via the `stable-repo-url` parameter.
