### ISSUE TITLE
Update to latest odk/orb-tools-orb

### ISSUE THREAD

**Issue by dsayling** [CircleCI-Public/helm-orb#36]
This orb has some tagging/release process that differs from the release used in the https://github.com/CircleCI-Public/Orb-Project-Template

This can lead to delayed releases for those that don't understand the release process.

**Comment by gmemstr** [comment]
https://github.com/CircleCI-Public/helm-orb/blob/master/.circleci/config.yml#L20

7.3 is the oldest version I've seen so far - going to work on updating that to v10 asap.
