### ISSUE TITLE
Allow passing of checksum for install script

### ISSUE THREAD

**Issue by tdeekens** [CircleCI-Public/helm-orb#48]
## Add parameter allowing to verify checksum 

The download script using a raw GitHub URL to download an install script and execute it. It could be preferred to additionally control the checksum of the downloaded and then installed binary to ensure it has not been manipulated or corrupt.

**Comment by brivu** [comment]
Hey @tdeekens, 

Thanks for opening this issue. I took look at the [install script](https://github.com/helm/helm/blob/ef02cafdd0a0be75b1f83f1b2c9ca4d1ac3edda5/scripts/get-helm-3#L147-L162) from that's downloaded from `Helm` and it already includes a function to check the `checksum`:

```
verifyFile() {
  if [ "${VERIFY_CHECKSUM}" == "true" ]; then
    verifyChecksum
  fi
  if [ "${VERIFY_SIGNATURES}" == "true" ]; then
    verifySignatures
  fi
}
```

Hopefully that's sufficient but feel free to open this issue again if you have any questions or clarifications. 

Thanks!
Brian
