### ISSUE TITLE
values-to-override can't handle environment variables

### ISSUE THREAD

**Issue by maximgtoy** [CircleCI-Public/helm-orb#50]
### Orb version

2.0.0

### What happened

The parameter values-to-override can't handle environment variables anymore in the new orb version.

### Expected behavior

I used to pass environment vars like this:
`values-to-override: image.tag=0.0.${CIRCLE_SHA1},image.repository=${AWS_ECR_ACCOUNT_URL}/<< parameters.repository >>`,
and get the following output in the chart:
```
image:
  repository: ACCOUNT.dkr.ecr.REGION.amazonaws.com/my_repo
  tag: 0.0.RANDOM_SHA1

```
### What's broken

Instead, I'm getting this now:
```
image:
  repository: $AWS_ECR_ACCOUNT_URL/my_repo
  tag: 0.0.$CIRCLE_SHA1

```
I tried manipulating the strings in a lot of variations, and nothing helped.

I'd be glad to get a quick response, I can even contribute if needed.
This currently takes down my deployments and I will probably revert the orb version to 1.2.0 again until a fix will be available.

**Comment by dseravalli** [comment]
2.0.0 can't handle env vars being passed into its commands it seems. It doesn't expand them like 1.2.0 did. I guess because 2.0.0 uses the `environment` key on the `run` step wheras 1.2.0 used the params directly in the script.

Works on 1.2.0 but broken on 2.0.0:
```
        - helm/upgrade-helm-chart:
            values: "/home/circleci/project/$MY_ENV_VAR"
            ...
```
