### ISSUE TITLE
Empty KUBERNETES_EXEC_INFO, defaulting to client.authentication.k8s.io/v1alpha1

### ISSUE THREAD

**Issue by caraways** [CircleCI-Public/helm-orb#51]
### Orb version

circleci/helm@1.2.0

### What happened

On the last step: ERROR

Empty KUBERNETES_EXEC_INFO, defaulting to client.authentication.k8s.io/v1alpha1. This is likely a bug in your Kubernetes client. Please update your Kubernetes client.
Error: Kubernetes cluster unreachable: Get https://*redacted**.*********.eks.amazonaws.com/version?timeout=32s: getting credentials: exec plugin is configured to use API version client.authentication.k8s.io/v1beta1, plugin returned version client.authentication.k8s.io/v1alpha1

Exited with code exit status 1
CircleCI received exit code 1

### Expected behavior

The helm chart would update successfully if working as expected.
Authentication with client.authentication.k8s.io/v1alpha1 was not an issue before 5/9/2022
We are using AWS EKS v1.19.15.

**Comment by ngutzmann** [comment]
The workaround we are using is to add the following environment variable to the affected job of the build:
```
environment
      KUBERNETES_EXEC_INFO: "{\"apiVersion\":\"client.authentication.k8s.io/v1beta1\"}"
```

**Comment by caraways** [comment]
We updated our helm-version. 

helm-version: v3.6.3

This resolved our error. We are still using circleci/helm@1.2.0 

We could not upgrade to circleci/helm@2.0.0 because of bug #50 (values-to-override can't handle environment variables #50)

**Comment by dseravalli** [comment]
We got this as well (on both version 1.2.0 and 2.0.0 of the orb). The issue is a new version of the AWS CLI that was recently released. Pinning our CLI version to 2.6.2 fixes the problem.
