### ISSUE TITLE
upgrade-helm-chart command is broken for charts without a repo

### ISSUE THREAD

**Issue by amitg-dt** [CircleCI-Public/helm-orb#54]
### What happened

Cannot do helm upgrade to a local chart (which is not in any repo) since `add-repo` variable is mandatory and forcing to do "helm repo add" with the same release name supplied to "helm install" - so I  can't even work around it with just giving stable chart.

```
        helm repo add "${ORB_PARAM_RELEASE_NAME}" "${ORB_PARAM_REPO}"
        helm repo update
        helm upgrade --install "${ORB_PARAM_RELEASE_NAME}" "${ORB_PARAM_CHART}"
```

This behavior changed from v1.2.0 without considering the case of private chart without a repo. 

### Expected behavior
There should be a parameter which allow do disable the repo add/update command, and the `add-repo` param needs to be optional.

**Comment by jeremysteele** [comment]
➕  This seems like a major oversight for private charts, and is badly blocking a deploy project I am on from using the orb. Only workaround I can find is to go back to manual helm commands, unfortunately.
