### ISSUE TITLE
parameter `add-repo` is mandatory in v2

### ISSUE THREAD

**Issue by yanns** [CircleCI-Public/helm-orb#57]
When updating from the version 1 to version 2 (1.2.0 -> 2.0.1), the command `helm/upgrade-helm-chart` is failing as it now needs the parameter `add-repo`.
We don't need that.

Do you expect users to set some unused value and set `update-repositories` to `true`?
Or can this parameter be optional?

**Comment by amitg-dt** [comment]
Same issue as mine #54
